export const BUTTON_TEXT = {
    BACK: "BACK",
    ADD_NEW_COURSE: "ADD NEW COURSE",
    SHOW_COURSE: "SHOW COURSE",
    LOGOUT: "LOGOUT",
    LOGIN: "LOGIN",
    REGISTER: "REGISTER",
    CANCEL: "CANCEL",
    CREATE_COURSE: "CREATE COURSE",
    CREATE_AUTHOR: "CREATE AUTHOR",
    SEARCH: "SEARCH",
    UPDATE_COURSE: "UPDATE COURSE",
};
